export const ENCRYPTION_CONTEXT = {
  glossarySource: "glossary_terms.source_text",
  glossaryTarget: "glossary_terms.target_text",
  glossaryDescription: "glossary_terms.description",
  glossaryForbidden: "glossary_terms.forbidden_terms",
  glossaryChange: "operation_logs.glossary_change",
  personJapanese: "people.japanese_canonical",
  personKorean: "people.korean_canonical",
  personAlias: "person_aliases.alias",
  toneRecommended: "tone_rules.recommended_tone",
  toneCushion: "tone_rules.cushion_phrases",
  toneForbidden: "tone_rules.forbidden_phrases",
  toneExample: "tone_rules.example",
  toneChange: "operation_logs.tone_change",
  translationSource: "translation_jobs.source_text",
  translationFinal: "translation_jobs.final_text",
  translationOutput: "translation_outputs.output_text",
  translationRecovery: "process_memory.translation_recovery",
  ruleSnapshot: "applied_rule_snapshots.snapshot",
} as const;
