import type { TranslationDirection } from "@/lib/language";

export type QualityEvaluationCase = {
  id: string;
  direction: TranslationDirection;
  sourceText: string;
  expectedText: string;
  requiredTerms: string[];
};

export const QUALITY_EVALUATION_CASES: readonly QualityEvaluationCase[] = [
  {
    id: "KO-JA-01",
    direction: "ko-ja",
    sourceText: "안녕하세요. 회의 일정을 확인 부탁드립니다.",
    expectedText: "こんにちは。会議の日程をご確認いただけますでしょうか。",
    requiredTerms: [],
  },
  {
    id: "KO-JA-02",
    direction: "ko-ja",
    sourceText: "이시와타리 대표님, Ontos 연습 계정 권한 확인을 부탁드립니다.",
    expectedText: "石渡さん、Ontos（IAM）の練習用アカウント権限をご確認いただけますでしょうか。",
    requiredTerms: ["石渡さん", "Ontos（IAM）"],
  },
  {
    id: "KO-JA-03",
    direction: "ko-ja",
    sourceText: "오늘 오후 3시까지 검토 의견을 보내 주세요.",
    expectedText: "本日午後3時までにレビューコメントをお送りください。",
    requiredTerms: [],
  },
  {
    id: "KO-JA-04",
    direction: "ko-ja",
    sourceText: "내일 오전 10시에 온라인 회의를 시작하겠습니다.",
    expectedText: "明日の午前10時にオンライン会議を開始します。",
    requiredTerms: [],
  },
  {
    id: "KO-JA-05",
    direction: "ko-ja",
    sourceText: "첨부한 견적서의 금액과 납기를 확인해 주세요.",
    expectedText: "添付した見積書の金額と納期をご確認ください。",
    requiredTerms: [],
  },
  {
    id: "KO-JA-06",
    direction: "ko-ja",
    sourceText: "ENSAPIA 주간 보고서를 금요일까지 공유하겠습니다.",
    expectedText: "ENSAPIAの週次報告書を金曜日までに共有します。",
    requiredTerms: ["ENSAPIA"],
  },
  {
    id: "KO-JA-07",
    direction: "ko-ja",
    sourceText: "Project Aurora의 2차 테스트가 완료되었습니다.",
    expectedText: "Project Auroraの第2次テストが完了しました。",
    requiredTerms: ["Project Aurora"],
  },
  {
    id: "KO-JA-08",
    direction: "ko-ja",
    sourceText: "자료 3개 중 2개를 먼저 전달드립니다.",
    expectedText: "資料3点のうち2点を先にお送りします。",
    requiredTerms: [],
  },
  {
    id: "KO-JA-09",
    direction: "ko-ja",
    sourceText: "회신이 늦어져 죄송합니다.",
    expectedText: "ご返信が遅くなり、申し訳ございません。",
    requiredTerms: [],
  },
  {
    id: "KO-JA-10",
    direction: "ko-ja",
    sourceText: "제안해 주신 일정으로 진행하기는 어렵습니다.",
    expectedText: "ご提案いただいた日程で進めることは難しい状況です。",
    requiredTerms: [],
  },
  {
    id: "KO-JA-11",
    direction: "ko-ja",
    sourceText: "확인해 주셔서 감사합니다.",
    expectedText: "ご確認いただき、ありがとうございます。",
    requiredTerms: [],
  },
  {
    id: "KO-JA-12",
    direction: "ko-ja",
    sourceText: "Slack 채널에 최종 파일을 올렸습니다.",
    expectedText: "Slackチャンネルに最終ファイルをアップロードしました。",
    requiredTerms: ["Slack"],
  },
  {
    id: "KO-JA-13",
    direction: "ko-ja",
    sourceText: "API 버전 2.4.0으로 업데이트해 주세요.",
    expectedText: "APIバージョン2.4.0に更新してください。",
    requiredTerms: ["API"],
  },
  {
    id: "KO-JA-14",
    direction: "ko-ja",
    sourceText: "이번 달 예산은 1,500달러입니다.",
    expectedText: "今月の予算は1,500ドルです。",
    requiredTerms: [],
  },
  {
    id: "KO-JA-15",
    direction: "ko-ja",
    sourceText: "계약서 초안을 법무팀에 전달했습니다.",
    expectedText: "契約書の草案を法務チームに送付しました。",
    requiredTerms: [],
  },
  {
    id: "KO-JA-16",
    direction: "ko-ja",
    sourceText: "수정 사항은 노란색으로 표시했습니다.",
    expectedText: "修正箇所は黄色で表示しました。",
    requiredTerms: [],
  },
  {
    id: "KO-JA-17",
    direction: "ko-ja",
    sourceText: "고객에게 보내기 전에 한 번 더 검토해 주세요.",
    expectedText: "お客様に送る前に、もう一度ご確認ください。",
    requiredTerms: [],
  },
  {
    id: "KO-JA-18",
    direction: "ko-ja",
    sourceText: "현재 서버는 정상적으로 작동하고 있습니다.",
    expectedText: "現在、サーバーは正常に稼働しています。",
    requiredTerms: [],
  },
  {
    id: "KO-JA-19",
    direction: "ko-ja",
    sourceText: "오류 원인을 확인한 뒤 다시 안내드리겠습니다.",
    expectedText: "エラーの原因を確認したうえで、改めてご案内します。",
    requiredTerms: [],
  },
  {
    id: "KO-JA-20",
    direction: "ko-ja",
    sourceText: "신규 계정 5개를 생성해 주세요.",
    expectedText: "新規アカウントを5件作成してください。",
    requiredTerms: [],
  },
  {
    id: "KO-JA-21",
    direction: "ko-ja",
    sourceText: "DemoDesk 신청서를 승인했습니다.",
    expectedText: "DemoDeskの申請書を承認しました。",
    requiredTerms: ["DemoDesk"],
  },
  {
    id: "KO-JA-22",
    direction: "ko-ja",
    sourceText: "회의실은 8층 A룸으로 변경되었습니다.",
    expectedText: "会議室は8階のAルームに変更されました。",
    requiredTerms: [],
  },
  {
    id: "KO-JA-23",
    direction: "ko-ja",
    sourceText: "가능하시다면 오늘 중으로 답변 부탁드립니다.",
    expectedText: "可能でしたら、本日中にご回答いただけますでしょうか。",
    requiredTerms: [],
  },
  {
    id: "KO-JA-24",
    direction: "ko-ja",
    sourceText: "배포 일정은 9월 15일로 확정되었습니다.",
    expectedText: "リリース日は9月15日に確定しました。",
    requiredTerms: [],
  },
  {
    id: "KO-JA-25",
    direction: "ko-ja",
    sourceText: "추가 질문이 있으면 언제든지 말씀해 주세요.",
    expectedText: "追加のご質問がありましたら、いつでもお知らせください。",
    requiredTerms: [],
  },
  {
    id: "JA-KO-01",
    direction: "ja-ko",
    sourceText: "お世話になっております。資料をご確認ください。",
    expectedText: "안녕하세요. 자료를 확인해 주세요.",
    requiredTerms: [],
  },
  {
    id: "JA-KO-02",
    direction: "ja-ko",
    sourceText: "本日の会議は午後4時からです。",
    expectedText: "오늘 회의는 오후 4시부터입니다.",
    requiredTerms: [],
  },
  {
    id: "JA-KO-03",
    direction: "ja-ko",
    sourceText: "明日の午前11時までにご返信ください。",
    expectedText: "내일 오전 11시까지 회신해 주세요.",
    requiredTerms: [],
  },
  {
    id: "JA-KO-04",
    direction: "ja-ko",
    sourceText: "添付ファイルを3点お送りします。",
    expectedText: "첨부 파일 3개를 보내드립니다.",
    requiredTerms: [],
  },
  {
    id: "JA-KO-05",
    direction: "ja-ko",
    sourceText: "ご対応いただき、ありがとうございます。",
    expectedText: "대응해 주셔서 감사합니다.",
    requiredTerms: [],
  },
  {
    id: "JA-KO-06",
    direction: "ja-ko",
    sourceText: "回答が遅くなり、申し訳ございません。",
    expectedText: "답변이 늦어져 죄송합니다.",
    requiredTerms: [],
  },
  {
    id: "JA-KO-07",
    direction: "ja-ko",
    sourceText: "ENSAPIAの月次レポートを共有します。",
    expectedText: "ENSAPIA 월간 보고서를 공유합니다.",
    requiredTerms: ["ENSAPIA"],
  },
  {
    id: "JA-KO-08",
    direction: "ja-ko",
    sourceText: "Ontos（IAM）の権限を確認しました。",
    expectedText: "Ontos 연습 계정의 권한을 확인했습니다.",
    requiredTerms: ["Ontos"],
  },
  {
    id: "JA-KO-09",
    direction: "ja-ko",
    sourceText: "Project Auroraのテストは完了しました。",
    expectedText: "Project Aurora 테스트가 완료되었습니다.",
    requiredTerms: ["Project Aurora"],
  },
  {
    id: "JA-KO-10",
    direction: "ja-ko",
    sourceText: "Slackに議事録を投稿しました。",
    expectedText: "Slack에 회의록을 게시했습니다.",
    requiredTerms: ["Slack"],
  },
  {
    id: "JA-KO-11",
    direction: "ja-ko",
    sourceText: "APIバージョン2.4.0をご利用ください。",
    expectedText: "API 버전 2.4.0을 사용해 주세요.",
    requiredTerms: ["API"],
  },
  {
    id: "JA-KO-12",
    direction: "ja-ko",
    sourceText: "見積金額は2,000ドルです。",
    expectedText: "견적 금액은 2,000달러입니다.",
    requiredTerms: [],
  },
  {
    id: "JA-KO-13",
    direction: "ja-ko",
    sourceText: "納期を9月20日に変更できますか。",
    expectedText: "납기를 9월 20일로 변경할 수 있을까요?",
    requiredTerms: [],
  },
  {
    id: "JA-KO-14",
    direction: "ja-ko",
    sourceText: "契約書の最終版をご確認ください。",
    expectedText: "계약서 최종본을 확인해 주세요.",
    requiredTerms: [],
  },
  {
    id: "JA-KO-15",
    direction: "ja-ko",
    sourceText: "修正箇所を赤色で表示しました。",
    expectedText: "수정한 부분을 빨간색으로 표시했습니다.",
    requiredTerms: [],
  },
  {
    id: "JA-KO-16",
    direction: "ja-ko",
    sourceText: "この日程で進めることは難しい状況です。",
    expectedText: "이 일정으로 진행하기는 어려운 상황입니다.",
    requiredTerms: [],
  },
  {
    id: "JA-KO-17",
    direction: "ja-ko",
    sourceText: "来週、改めて打ち合わせをお願いします。",
    expectedText: "다음 주에 다시 회의를 부탁드립니다.",
    requiredTerms: [],
  },
  {
    id: "JA-KO-18",
    direction: "ja-ko",
    sourceText: "サーバーは正常に稼働しています。",
    expectedText: "서버는 정상적으로 작동하고 있습니다.",
    requiredTerms: [],
  },
  {
    id: "JA-KO-19",
    direction: "ja-ko",
    sourceText: "原因を調査してからご連絡します。",
    expectedText: "원인을 조사한 뒤 연락드리겠습니다.",
    requiredTerms: [],
  },
  {
    id: "JA-KO-20",
    direction: "ja-ko",
    sourceText: "新しいアカウントを5件作成しました。",
    expectedText: "새 계정 5개를 생성했습니다.",
    requiredTerms: [],
  },
  {
    id: "JA-KO-21",
    direction: "ja-ko",
    sourceText: "DemoDeskの申請を承認してください。",
    expectedText: "DemoDesk 신청을 승인해 주세요.",
    requiredTerms: ["DemoDesk"],
  },
  {
    id: "JA-KO-22",
    direction: "ja-ko",
    sourceText: "会議室は8階のBルームです。",
    expectedText: "회의실은 8층 B룸입니다.",
    requiredTerms: [],
  },
  {
    id: "JA-KO-23",
    direction: "ja-ko",
    sourceText: "本日中にご回答いただけますでしょうか。",
    expectedText: "오늘 중으로 답변해 주실 수 있을까요?",
    requiredTerms: [],
  },
  {
    id: "JA-KO-24",
    direction: "ja-ko",
    sourceText: "リリース日は10月1日に決定しました。",
    expectedText: "배포일은 10월 1일로 결정되었습니다.",
    requiredTerms: [],
  },
  {
    id: "JA-KO-25",
    direction: "ja-ko",
    sourceText: "ご不明な点があれば、いつでもお知らせください。",
    expectedText: "궁금한 점이 있으면 언제든지 말씀해 주세요.",
    requiredTerms: [],
  },
];
